### PR TITLE
Create 221015-FirstTweetSuggestion.tweet

### PR DESCRIPTION
**Pull request by w1g0**

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
Wording is a bit strange, twitter-together is the name of the github action, I think we need to make it clear something like "Ethereum Classic Twitter Accounts @eth_classic and @ETC_Network are open to tweet suggestions ... "

**Comment by IstoraMandiri** [comment]
Also notice the weird hashtag formatting which would appear when tweeting.

Perhaps we should just rename the discord channel to TweetSuggestions

**Comment by w1g0** [comment]
> Wording is a bit strange, twitter-together is the name of the github action, I think we need to make it clear something like "Ethereum Classic Twitter Accounts @eth_classic and @ETC_Network are open to tweet suggestions ... "
> 
> Also please use double spacing between lines.

I like the Twitter-Together name, people generally don't know that it is the name of the GitHub action.
K.I.S.S. Keep It Stupid Simple

Twitter invites them in Discord there you lay out the distinction.

**Comment by w1g0** [comment]
> Also notice the weird hashtag formatting which would appear when tweeting.
> 
> Perhaps we should just rename the discord channel to TweetSuggestions

That was a little test of mine, I renamed the hashtag to see what happens.

**Comment by IstoraMandiri** [comment]
Oh right, I see, you are referring to the twitter-together Discord channel, but seems confusing when we can point them directly to the thread.

```
The @eth_classic and @ETC_Network are now accepting suggestions for tweets via Discord!

Join https://discord.gg/ethereumclassic and suggest a tweet! hugs
```

**Comment by w1g0** [comment]
I refer to Twitter-Together as a feature, we all Tweet together 🤗
@bobsummerwill also used it to spread awareness, it's catchy and great marketing term imho.

**Comment by IstoraMandiri** [comment]
Yes, Bob used it, but not to refer to our project:

https://twitter.com/eth_classic/status/1580266564133208064

**Comment by w1g0** [comment]
You're right, he used “tweeting together” which is even better! 💪
https://twitter.com/eth_classic/status/1579334928336097280

**Comment by IstoraMandiri** [comment]
So how about

```
We are now tweeting together in the #ETCTweetSuggestions thread on Discord.

Join https://discord.gg/ethereumclassic and suggest a tweet for `@eth_classic` and `@ETC_Network`! hugs

[#EthereumClassic](https://twitter.com/search?q=%23EthereumClassic)
```

**Comment by IstoraMandiri** [comment]
Edit, we should include "Or use the hashtag Blah blah "

**Comment by w1g0** [comment]
> Edit, we should include "Or use the hashtag Blah blah "

Yes, my thoughts exactly!

**Comment by IstoraMandiri** [comment]
@w1g0 shall we update this tweet with the new wording and info about the #ETCtweets hahtaga?

**Pull request closed without merging**
