### PR TITLE
Create 221020-GrainOfSand.tweet

### PR DESCRIPTION
**Pull request by w1g0**

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
You need to remove thte extra params like `?s=`

**Comment by w1g0** [comment]
> You need to remove thte extra params like `?s=`

Is that referenced in the manual? I didn't see that.

**Comment by IstoraMandiri** [comment]
Not sure this a good one to tweet out. Nice that ETC is getting mentioned but comparing SHA256 TH/s to Scrypt / ETHash TH/s is pretty misleading.

**Comment by IstoraMandiri** [comment]
Yes, in https://github.com/ethereumclassic/tweets-eth_classic/pull/32 but not merged yet.

**Comment by w1g0** [comment]
> Not sure this a good one to tweet out. Nice that ETC is getting mentioned but comparing SHA256 TH/s to Scrypt / ETHash TH/s is pretty misleading.

I think any comparison with BTC is beneficial and the fact that Michael Saylor mentions ETC is awesome but that's just my opinion. It's about @ETCPOW's tweet not so much about the content of the original clip but I understand it's not political correct. On the other hand it's not ``@Eth_Classic`` account either. Let's see what other reviewers bring to the table. Soon we'll have to raise the number of reviews and push active reviewers.

**Comment by IstoraMandiri** [comment]
"Shitcoin" breaks other rules also

**Comment by w1g0** [comment]
> * We should definitely take into consideration the content of the retweeted tweet
> * "Shitcoin" breaks other rules also

We share the same sentiment but I figured "shitcoin" is an official crypto term 😂

**Pull request closed without merging**
