### PR TITLE
Add god tweet

### PR DESCRIPTION
**Pull request by IstoraMandiri**

### CODE REVIEW

**Comment by w1g0** [comment]
We should add in the rules that referring to any kind of ineligible is.

**Comment by IstoraMandiri** [comment]
> We should add in the rules that referring to any kind of ineligible is.

?

**Review by brolal — APPROVED** [review]

**Comment by brolal** [comment]
> We should add in the rules that referring to any kind of religion is ineligible.

why would we want to complicate stuff?

**Comment by brolal** [comment]
in the end, we are approving thoughts submitted by the community. They wont always match our way of thinking, but we can respect different views as long as they are not expressed in a harmful, imo
drafting rulz for speech control is a waste of time

**Comment by brolal** [comment]
LGTM

**Pull request merged**
