### PR TITLE
Create Tweet: 221106-force-of-nature.tweet

### PR DESCRIPTION
**Pull request by IstoraMandiri**
Approve but don't merge yet please.

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]

**Review by brolal — APPROVED** [review]

**Comment by w1g0** [comment]
@brolal is a loose cannon 😂

**Comment by brolal** [comment]
> 

huh?

**Comment by w1g0** [comment]
> Approve but don't merge yet please.

@brolal 👆

**Comment by brolal** [comment]
> 

ah, missed that

**Pull request merged**
