### PR TITLE
Create 221022-retweet-shibcmemes-meme.tweet

### PR DESCRIPTION
**Pull request by shibcmemes**
Sorry for any mess I might have made with this - I am but a simple shib, still learning how to do serious things :)

### CODE REVIEW

**Review by TheCrowbill — COMMENTED** [review]
While funny, I don't think this meets even the loosest criteria for a retweet.

**Comment by shibcmemes** [comment]
https://github.com/ethereumclassic/tweets-etc_network/issues/90#issue-1406968465

"presumably with less restrictions and more memes and/or project promotion."

I am glad you think it's funny - I didn't mean to be rude (we're clean and tidy and do respect the "lawn").
It's both intended as a light hearted meme and some promotion for both the eco and SHIBC.

I fail to see how "ETC is a gift from God" is any better, divisive, really.

**Comment by IstoraMandiri** [comment]
When submitting tweets from #ETCtweets, please copy the content of the tweet rather than retweeting.

**Comment by shibcmemes** [comment]
> I think this would be OK if it was specific to ETC rather than Shiba Classic.

It tells the world why we're here. on ETC, and why that's important 

Code is Law isn't a slogan or a meme, it's a righteous statement and commitment - it's serious.

I don't consider it a gift, but a responsibility.

That's the juxtaposition - the serious meme, and SHIBC intends to "bark" this at everyone.

No disrespect was intended with this, just some meme flavour, ie: coleslaw, code is lawn, etc.

**Comment by IstoraMandiri** [comment]
> It tells the world why we're here on ETC, and why that's important

This twitter account is about Ethereum Classic itself, and we are avoiding promoting third party projects unless linked to via the ethereumclassic.org website, as it contains disclaimers.

It would be fine if it wasn't promoting Shiba Classic.

**Comment by shibcmemes** [comment]
> This twitter account is about Ethereum Classic itself, and we are avoiding promoting third party projects unless linked to via the ethereumclassic.org website, as it contains disclaimers.

So it's a centralised thing to go through another centralised thing to hit Twitter, which is more decentralised than both 1) applying for the website (which we'll do, sure) and 2) using this repo, something you put on Twitter to encourage engagement with - which I have! 

Today I've uploaded all of the great SHIBC memes and ETC resources to GitHub so other people can do the same for whatever they are working on, and continue to grow and promote the ecosystem - hopefully this can benefit the eco in itself.

But where does promoting *God* fall into this? Which God? Religious baiting is some of the most known troll activity on the internet (even asking this, I feel like I'm trolling). That's the optics of that Tweet.

It completely undermines the effort and dedication to maintaining "Code is Law" - it wasn't a gift, it was responsibility forced when a centralised group decided to roll back what was meant to be immutable, few people stood up and more continue to join - that's more righteous than any religious/God based crusade I've ever learned of.

You could interact with projects on your ecosystem instead you're gatekeeping even retweeting a meme.

> IMO it would be fine if it wasn't promoting Shiba Classic.

It promotes ETC *and* SHIBC, and ETC is first - it's not my fault this dawgy can poop gems, again, we tidy up after it, we bring our bags.

I close this out with this, at this point, I don't even care for the meme. It's not even funny.

**Pull request closed without merging**
